#ifndef __MIX_PARSER_MIX_AST_NODE_TYPE_H__
#define __MIX_PARSER_MIX_AST_NODE_TYPE_H__

#include <stdint.h>

enum {
    MIX_AST_NODE_TYPE_VAR_DECL,
    MIX_AST_NODE_TYPE_BRANCH,
    MIX_AST_NODE_TYPE_BINOP,
    MIX_AST_NODE_TYPE_NODE_LIST,
    MIX_AST_NODE_TYPE_EXP,
    MIX_AST_NODE_TYPE_IMPORT,
    MIX_AST_NODE_TYPE_IMPORT_ALIAS,
    MIX_AST_NODE_TYPE_FUNCALL,
    MIX_AST_NODE_TYPE_UNKNOWN,
};

typedef uint32_t mix_ast_node_type_t;

#endif
